[workspace]
name = "google_earth_engine_env"
channels = ["knime/label/nightly", "knime", "conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
knime-extension = ">=5.5.0"
knime-python-versions = ">=5.7.0"
geemap = "0.35.3.*"
geopandas = "1.1.1.*"

[feature.build.dependencies]
python = "3.9.*"
knime-extension-bundling = "5.7.*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "build-python-extension . {{ dest }}"}

[environments]
build = {features = ["build"], no-default-feature = true}